# PerfectFireball 配置文件

# 火球速度倍率 (默认: 1.0)
# 值越大，火球飞行速度越快
fireball-speed-multiplier: 1.0

# 火球超时时间 (秒) (默认: 20)
# 火球在发射后经过指定时间未命中目标将自动消失
# 设置为0表示永不超时
fireball-timeout: 20

# 冷却时间 (tick) (默认: 16,0.8s)
# 玩家发射火球后的冷却时间，20 ticks = 1秒
# 设置为0表示无冷却
cooldown-ticks: 16

# 是否破坏方块 (默认: false)
# 设置为true时，火球爆炸会破坏方块，爆炸强度由 explosion-power 控制
destroy-blocks: false

# 是否伤害实体 (默认: false)
# 设置为 true 时，火球爆炸会伤害实体（玩家、生物等）伤害由 explosion-power 控制
damage-entities: false

# 击飞强度 (默认: 2.0)
# 值越大，被击飞的实体飞得越远
knockback-power: 4.5

# 击飞范围 (默认: 5.0)
# 火球爆炸后，在此 火球爆炸后，在此范围内的实体会被击飞
knockback-radius: 5.0

# 爆炸视觉效果强度 (默认: 0.0)
# 控制爆炸的视觉效果（声音、粒子），不影响实际破坏
# 设置为0.0时无视觉效果，最大值为4.0（相当于TNT）
explosion-power: 0.0